#!/usr/bin/env python3

import argparse
import os
import re

# parses command line arguments
# sample command: importanceKappa -c file1.xml file2.xml
parser = argparse.ArgumentParser(description="calculates Cohen's Kappa scores from CompanionBot Importance annotations")
parser.add_argument('-H', '--csv-header', action='store_true', dest='csv_header', help='print the header line for stats in CSV format to terminal: (file1,file2,total,agreement,chance,kappa_score)')
parser.add_argument('-c', '--csv-output', action='store_true', dest='csv_output_mode', help='print stats in CSV format to terminal: (file1,file2,total,agreement,chance,kappa_score)')
parser.add_argument('source1', type=str, help='the first source annotation file')
parser.add_argument('source2', type=str, help='the second source annotation file')

args = parser.parse_args()
sources = [args.source1, args.source2]

for source in range(len(sources)):
    sources[source] = os.path.abspath(re.sub(""""|'""",'', sources[source]))

#texts = {source: open(source).read() for source in sources}
texts = {source: source[0:4] for source in sources}

for source in sources: print(texts[source])
